repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      #- id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: '^[requirements]\.txt$'
      - id: fix-encoding-pragma
      - id: flake8
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.15
#    hooks:
#      - id: isort
  - repo: https://github.com/pre-commit/mirrors-puppet-lint
    rev: v2.4.2
    hooks:
      - id: puppet-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        files: '\.(py|sh|md|yaml)$'
      - id: remove-tabs
        files: '\.(py|sh|md|yaml)$'
        args: [ --whitespaces-count, '2' ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
      - id: dockerfile_lint
      - id: markdown-toc
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.20.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
        language_version: python3
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.20.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.5.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
      - id: pylint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.2
    hooks:
      - id: bundler-audit
      - id: check-mailmap
      - id: fasterer
      - id: forbid-binary
      #  id: forbid-space-in-indent
      - id: git-check  # Configure in .gitattributes
      #  id: git-dirty  # Configure in .gitignore
      - id: reek
      #  id: require-ascii
      - id: rubocop
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
        args: [-e, SC2086]
      - id: shfmt
### Init Error: .pre-commit-hooks.yaml does not exist
#  - repo: git://github.com/detailyang/pre-commit-shell
#    rev: 1.0.1
#    hooks:
#      - id: shell-lint
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
  - repo: meta
    hooks:
#      - id: check-hooks-apply
      - id: check-useless-excludes
